# Generated by Django 5.2.5 on 2025-09-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=2),
        ),
    ]
